title: Experimental Sounds Finland
description:
  A calendar for experimental sound events in Finland
author:
  name: Libero Mureddu & Andrea Mancianti
baseurl: ""
url: experimentalsoundingfinland.github.io
remote_theme: jekyll/minima
header_pages:
  - index.md
  - about_fi.md
  - about_en.md
minima:
skin: auto

